# render.yaml
previews:
  generation: automatic # Génération automatique des prévisualisations pour les pull requests

services:
  # Backend Service (Node.js WebSocket Server)
  - type: web
    name: collaborative-dashboard-backend
    env: node
    plan: free # Utilise le plan gratuit de Render
    buildCommand: npm install # Installe les dépendances du backend
    startCommand: node server/index.js # Démarre le serveur Node.js
    # ports: # Cette ligne et la suivante doivent être supprimées
    #   - 8080 
    # autoDeploy: true # Render déploie automatiquement par défaut pour les nouveaux services

  # Frontend Service (React Static Site)
  - type: web
    name: collaborative-dashboard-frontend
    runtime: static
    plan: free # Utilise le plan gratuit de Render
    buildCommand: npm install && npm run build # Installe les dépendances et construit l'application React
    staticPublishPath: dist # Le répertoire où Vite génère les fichiers de build
    # autoDeploy: true # Render déploie automatiquement par défaut pour les nouveaux services
    envVars:
      - key: VITE_WEBSOCKET_URL
        value: wss://collaborative-dashboard-backend.onrender.com # URL sécurisée de votre service backend sur Render
